// <auto-generated />
using Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(ProjectAlfredContext))]
    [Migration("20220705175030_Create_MusicChannel_Entity")]
    partial class Create_MusicChannel_Entity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Domain.Entity.MusicChannel", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MusicChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("MusicChannels");
                });

            modelBuilder.Entity("Domain.Entity.SongRecord", b =>
                {
                    b.Property<string>("OriginalUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalPoster")
                        .HasColumnType("TEXT");

                    b.Property<int>("LikesCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnicornsCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("OriginalUrl", "OriginalPoster");

                    b.ToTable("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
